apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: mlossmann/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: mlossmann/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
    - image: mlossmann/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.js"
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yml
      - k8s/server-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/database-persistent-volume-claim.yml
      - k8s/ingress-service.yml
      - k8s/postgres-cluster-ip-service.yml
      - k8s/postgres-deployment.yml
      - k8s/redis-cluster-ip-service.yml
      - k8s/redis-deployment.yml
      - k8s/worker-deployment.yml
      - k8s/server-cluster-ip-service.yml
      - k8s/client-cluster-ip-service.yml
