apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nuagenet-net-tls
spec:
  secretName: nuagenet-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nuagenet.net
  dnsNames:
    - nuagenet.net
    - www.nuagenet.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - nuagenet.net
          - www.nuagenet.net
