apiVersion: certmanager.k8s.io/v1alpha1
kind: certificate
metadata:
  name: nuagenet-net-tls
spec:
  secretName: nuagenet-net ## where should cert be stored once certmgr gets cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nuagenet.net
  dnsNames:
    - www.nuagenet.net
  acme:
    config:
      -http01:
        ingressClass: nginx
      domains:
        - www.nuagenet.net
