apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-nuagenet-net-tls
spec:
  secretName: k8s-nuagenet-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nuagenet.net
  dnsNames:
    - www.nuagenet.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - www.nuagenet.net
